# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminalika" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "3b8962116ce124c8057e7dc87a597ab8d464f0f86de1abc0398ce0edb0a7fca4"
      url "https://github.com/terminalika/terminalika/releases/download/v#{version}/terminalika_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c775254ed099b8db19c4b957efa2637f8eca01c693f61f88df7f0ed4f1796d89"
      url "https://github.com/terminalika/terminalika/releases/download/v#{version}/terminalika_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "801d889b10aa946746e373a4ac3e20015ee640b0ea3c2ec77e11eda4b192f1e0"
      url "https://github.com/terminalika/terminalika/releases/download/v#{version}/terminalika_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "daf64b775cc0ee5af88d5f808c8df687cb758b63ea0ef727203a8f867a988ff6"
      url "https://github.com/terminalika/terminalika/releases/download/v#{version}/terminalika_#{version}_linux_amd64.tar.gz"
    end
  end

  name "terminalika"
  desc "Tiny terminal game launcher for AI-agent waiting time"
  homepage "https://github.com/terminalika/terminalika"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terminalika"

  # No zap stanza required
end
