# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminalika" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "43c6f23de7eb5064fa26574a37d526482d361639d9dc9a3ce315dc1bfc5fc1f1"
      url "https://github.com/terminalika/terminalika/releases/download/v#{version}/terminalika_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3a4f84ad2181271a2187843ce587196bd4c1c8135c2bf97d49f01486cb8a0aca"
      url "https://github.com/terminalika/terminalika/releases/download/v#{version}/terminalika_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1ecac976733a94646332a9ee6dab99918b6cb97f0f50ca10677d884ac0e65bd0"
      url "https://github.com/terminalika/terminalika/releases/download/v#{version}/terminalika_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "63232a44adb57183ea410bc5da58d108a937b599d4ca9538bb496302d9a6d504"
      url "https://github.com/terminalika/terminalika/releases/download/v#{version}/terminalika_linux_amd64.tar.gz"
    end
  end

  name "terminalika"
  desc "Tiny terminal game launcher for AI-agent waiting time"
  homepage "https://github.com/terminalika/terminalika"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terminalika"

  # No zap stanza required
end
