# This file was generated by GoReleaser. DO NOT EDIT.
cask "terminalika" do
  version "0.3.3"

  on_macos do
    on_arm do
      sha256 "f7c01ce09eb8f1c26daba416feaaf2d0cae51b1414bd368054fba880a9b36928"
      url "https://github.com/terminalika/terminalika/releases/download/v#{version}/terminalika_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b19a398df0732b8796d7cf932f2b15bee109c4a22a26df9eccdb69d8fb8a6d4"
      url "https://github.com/terminalika/terminalika/releases/download/v#{version}/terminalika_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "abb4d09741f74fa438d90ca242a77b587a05051b2463f7b768128026c6bb5d61"
      url "https://github.com/terminalika/terminalika/releases/download/v#{version}/terminalika_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a697c63e755b3928953a43e80c9ee8b721356577a9172399b108241022130ddd"
      url "https://github.com/terminalika/terminalika/releases/download/v#{version}/terminalika_#{version}_linux_amd64.tar.gz"
    end
  end

  name "terminalika"
  desc "Tiny terminal game launcher for AI-agent waiting time"
  homepage "https://github.com/terminalika/terminalika"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terminalika"

  # No zap stanza required
end
